#!/bin/sh

# WARNING:
# Running IntelliJ IDEA with java other than java 8
# may cause various problems, such as Graddle import not working
export XMODIFIERS="@im=fcitx"
export GTK_IM_MODULE="fcitx"
export QT_IM_MODULE="fcitx"
if [ -z "$IDEA_JDK" ] ; then
  IDEA_JDK="/usr/lib/jvm/java-8-openjdk/"
fi
exec env IDEA_JDK="$IDEA_JDK" /usr/share/idea/bin/idea.sh "$@"

# vim: ts=2 sw=2 et:
